name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 black
      
      - name: Compile Python
        run: python -m py_compile runner.py test_script.py
      
      - name: Check code style with Black
        run: black --check runner.py test_script.py || true
      
      - name: Lint with Pylint
        run: pylint runner.py --fail-under=7.0 || true
      
      - name: Lint with Flake8
        run: flake8 runner.py test_script.py --count --statistics || true
